INDUSTRY_LIST = [
    "Electric Equipment", "Logistics", "Packaging", "Batteries", "Pharmaceuticals & Drugs",
    "Finance - Housing", "Chemicals", "Construction - Real Estate", "Finance - Investment",
    "Hotel, Resort & Restaurants", "Bank - Private", "Textile", "Tea/Coffee",
    "Engineering - Industrial Equipments", "Auto Ancillary", "Consumer Durables - Domestic Appliances",
    "Sugar", "Automobiles-Trucks/Lcv", "Finance - NBFC", "Breweries & Distilleries",
    "Steel & Iron Products", "Diversified", "Pesticides & Agrochemicals", "Footwear",
    "Household & Personal Products", "Steel/Sponge Iron/Pig Iron", "Dyes & Pigments",
    "Construction Vehicles", "Defence", "Industrial Gases & Fuels", "Cable", "Air Conditioners",
    "Refineries", "Electronics - Components", "Fertilizers", "IT - Software",
    "Aluminium & Aluminium Products", "Power Generation/Distribution", "Ratings", "Textile - Spinning",
    "Automobiles - Passenger Cars", "Paper & Paper Products", "Petrochemicals",
    "Finance Term Lending", "Telecommunication - Service Provider", "Bank - Public",
    "Diamond & Jewellery", "Mining & Minerals", "Electrodes & Welding Equipment",
    "Plastic Products", "Transmission Towers / Equipments", "Ferro & Silica Manganese",
    "Business Support", "Cigarettes/Tobacco", "Trading", "Paints", "Tyres & Allied",
    "Automobile Two & Three Wheelers", "Telecom-Infrastructure", "Engineering - Construction",
    "Oil Exploration", "Metal - Non Ferrous", "TV Broadcasting & Software Production", "Glass",
    "Textile - Manmade Fibres", "Miscellaneous", "Compressors / Pumps", "Travel Services",
    "Environmental Services", "Edible Oil", "Textile - Weaving", "Consumer Food",
    "Ceramics/Marble/Granite/Sanitaryware", "Cement & Construction Materials", "Agriculture",
    "Castings/Forgings", "Retailing", "Textile - Machinery", "Lubricants", "Finance - Others",
    "Floriculture", "Leather", "Consumer Durables - Electronics", "Airlines", "Engineering",
    "IT - Education", "Wood & Wood Products", "Forgings", "Animation", "Rubber Products",
    "Finance - Stock Broking", "Automobiles-Tractors", "Telecommunication - Equipment",
    "Fasteners", "Solvent Extraction", "Diesel Engines", "Watches & Accessories",
    "Metal - Ferrous", "Bearings", "Shipping", "Medical Equipment/Supplies/Accessories",
    "Refractories", "BPO/ITeS", "Film Production, Distribution & Entertainment", "IT - Hardware",
    "Cycles", "Railways Wagons", "Abrasives", "Restaurants", "Hospital & Healthcare Services",
    "Carbon Black", "Detergents & Soaps", "Professional Services", "Educational Institutions",
    "Printing And Publishing", "Advertising & Media", "IT - Networking", "Animal Feed",
    "Aquaculture", "Printing & Stationery", "Courier Services", "Photographic Products",
    "Engineering Consultancy", "Amusement Parks/Recreation/Club", "Laminates/Decoratives",
    "Automobiles - Dealers & Distributors", "Ship Building", "Finance - Asset Management",
    "Gas Transmission/Marketing", "Airport Management Services", "Port", "Unspecified",
    "ETF", "Depository Services", "Fintech", "Insurance", "e-Commerce"
]